
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
template: !include template.yaml
script: !include scripts.yaml
automation: !include automations.yaml

climate:
  - platform: smartir
    name: Living Room AC
    unique_id: living_room_ac
    device_code: 9999
    controller_data: remote.living_room_rm4
    temperature_sensor: sensor.living_room_rm4_temp

  - platform: smartir
    name: Primary AC
    unique_id: primary_ac
    device_code: 9991
    controller_data: remote.primary_rm4
    temperature_sensor: sensor.primary_rm4_temp

  - platform: smartir
    name: Nursery AC
    unique_id: nursery_ac
    device_code: 9991
    controller_data: remote.nursery_rm4
    temperature_sensor: sensor.nursery_rm4_temp

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1